name: Deploy and Build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to DigitalOcean Droplets
    runs-on: ubuntu-latest

    env:
      DROPLET_1_IP: ${{ secrets.DROPLET_1_IP }}
      DROPLET_2_IP: ${{ secrets.DROPLET_2_IP }}
      SSH_USERNAME: root
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install SSHPass
      run: sudo apt-get install -y sshpass

    - name: Copy files to Droplet 1
      run: |
        sshpass -p $SSH_PASSWORD rsync -avz -e "ssh -o StrictHostKeyChecking=no" . $SSH_USERNAME@$DROPLET_1_IP:/root/EDGAR_Backend
        sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$DROPLET_1_IP 'cd /root/EDGAR_Backend && docker-compose build'

    - name: Copy files to Droplet 2
      run: |
        sshpass -p $SSH_PASSWORD rsync -avz -e "ssh -o StrictHostKeyChecking=no" . $SSH_USERNAME@$DROPLET_2_IP:root/EDGAR_Backend
        sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$DROPLET_2_IP 'cd /root/EDGAR_Backend && docker-compose build'
