version: '3'

services:
  ui_api:
    build:
      context: .
      dockerfile: Dockerfile_ui_api
    ports:
      - "8000:8000"
    volumes:
      - ./ui_api:/app/ui_api


  client_api:
    build:
      context: .
      dockerfile: Dockerfile_client_api
    ports:
      - "8001:8001"
    volumes:
      - ./client_api:/app/client_api
