FROM python:3.11

WORKDIR /app

# Copy specific directories and all files at the root level
COPY config /app/config
COPY edgar /app/edgar
COPY database /app/database
COPY helpers /app/helpers
COPY models /app/models
COPY ui_api /app/ui_api
COPY *.py /app/
COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

CMD ["uvicorn", "ui_api.main:app", "--host", "0.0.0.0", "--port", "443", "--ssl-certfile", "/etc/letsencrypt/live/api.equityexplorer.io/fullchain.pem", "--ssl-keyfile", "/etc/letsencrypt/live/api.equityexplorer.io/privkey.pem"]
