version: '3'

services:
  ui_api:
    build:
      context: .
      dockerfile: Dockerfile_ui_api
    ports:
      - "8000:8000"
#    ports:
#      - "443:443"
#    volumes:
#      - .:/app
#      - /etc/letsencrypt/live/api.equityexplorer.io:/etc/letsencrypt/live/api.equityexplorer.io:ro
#    network_mode: "bridge"
