version: '3'

services:
  ui_api:
    build:
      context: .
      dockerfile: Dockerfile_ui_api
    ports:
      - "443:443"
    volumes:
      - .:/app
      - /etc/letsencrypt/:/etc/letsencrypt:ro
    network_mode: "bridge"
    env_file:
      - ./config/.env
