FROM python:3.11

WORKDIR /app

COPY config /app/config
COPY edgar /app/edgar
COPY database /app/database
COPY helpers /app/helpers
COPY ui_api /app/ui_api
COPY *.py /app/

COPY requirements.txt /app/requirements.txt

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -i https://pypi.python.org/simple -r /app/requirements.txt

CMD ["uvicorn", "ui_api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
