version: '3'

services:
  ui_api:
    build:
      context: .
      dockerfile: Dockerfile_ui_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    network_mode: "bridge"

  client_api:
    build:
      context: .
      dockerfile: Dockerfile_client_api
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    network_mode: "bridge"
