# Dockerfile.ui_api
FROM python:3.11

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r /app/requirements.txt

CMD ["uvicorn", "ui_api.main:app", "--host", "0.0.0.0", "--port", "8000"]
