name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up doctl using the DigitalOcean GitHub Action
    - name: Set up doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    # Step 3: Set up Kubernetes config
    - name: Set up Kubernetes Config
      run: doctl kubernetes cluster kubeconfig save bagels-k8s-cluster

    # Step 4: Log in to the DigitalOcean Container Registry
    - name: Log in to DigitalOcean Container Registry
      run: echo "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" | docker login -u doctl --password-stdin registry.digitalocean.com

    # Step 5: Build Docker Image
    - name: Build Docker Image
      run: docker build -t registry.digitalocean.com/bagels/backend_service:latest .

    # Step 6: Push Docker Image
    - name: Push Docker Image
      run: docker push registry.digitalocean.com/bagels/backend_service:latest

    # Step 7: Deploy to Kubernetes
    - name: Deploy to Kubernetes
      run: kubectl apply -f deployment.yaml
